import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const baseURL=process.env.VAANI_BASE_URL||'http://127.0.0.1:4173/';
const launchOptions={headless:true,args:['--no-sandbox']};
if(process.env.VAANI_BROWSER_EXECUTABLE)launchOptions.executablePath=process.env.VAANI_BROWSER_EXECUTABLE;
const browser=await chromium.launch(launchOptions);
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const pageErrors=[],consoleErrors=[],failedRequests=[];
page.on('pageerror',error=>pageErrors.push(error.stack||error.message));
page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});
page.on('requestfailed',request=>failedRequests.push({url:request.url(),error:request.failure()?.errorText||'failed'}));
try{
 await page.goto(baseURL,{waitUntil:'domcontentloaded'});
 await page.waitForSelector('#gate-stage-start',{state:'visible',timeout:15000});
 await page.evaluate(()=>{generateCode=()=> '919191';});
 await page.locator('#cadetName').fill('Vocab90 QA');
 await page.locator('#gateBtn').click();
 await page.waitForSelector('#gate-stage-showcode',{state:'visible',timeout:15000});
 await page.locator('#gate-stage-showcode .gate-btn').click();
 await page.waitForSelector('#serviceForcePicker[data-mode="onboarding"]',{state:'visible',timeout:15000});
 await page.locator('#serviceForcePicker .service-force-option[data-force="army"]').click();
 await page.waitForFunction(()=>document.getElementById('gate')?.classList.contains('hide'),null,{timeout:15000});
 if(await page.locator('#viTour.open').count())await page.keyboard.press('Escape');
 await page.locator('#vaaniMainNav button[data-view="vocab"]').click();
 await page.waitForFunction(()=>document.getElementById('view-vocab')?.classList.contains('active'));
 await page.locator('#view-vocab .v90-entry-open').click();
 await page.waitForFunction(()=>document.getElementById('view-vocab90')?.classList.contains('active'));
 await page.waitForFunction(()=>Boolean(document.querySelector('#v90DayContent .v90-section-card'))||Boolean(document.getElementById('v90LoadError')&&!document.getElementById('v90LoadError').hidden),null,{timeout:15000}).catch(async error=>{const snapshot=await page.evaluate(()=>({active:document.getElementById('view-vocab90')?.className,day:document.getElementById('v90SelectedTitle')?.textContent,meta:document.getElementById('v90SelectedMeta')?.textContent,loadError:document.getElementById('v90LoadError')?.textContent,controller:typeof VAANI_VOCAB90,grid:document.getElementById('v90DayGrid')?.innerHTML.slice(0,500)}));console.error('Vocab90 load diagnostics:',JSON.stringify({snapshot,pageErrors,consoleErrors,failedRequests}));throw error;});
 const loadError=await page.locator('#v90LoadError').textContent();
 assert.equal(await page.locator('#v90LoadError').isHidden(),true,'Vocab90 reported a load error: '+loadError);
 await page.locator('#v90DayContent .v90-section-card').first().waitFor({state:'visible',timeout:5000});
 assert.equal(await page.locator('#v90SelectedTitle').innerText(),'Day 01');
 assert.equal(await page.locator('#v90DayGrid [data-v90-select]').count(),30);
 assert.equal(await page.locator('#view-vocab90 iframe').count(),0);
 const before=await page.evaluate(()=>Number(State.xp)||0);
 await page.locator('#v90MarkDone').click();
 await page.waitForFunction(()=>State.vocab90Completed['1']===true);
 const once=await page.evaluate(()=>({xp:State.xp,reward:State.vocab90XpAwarded['1']}));
 assert.equal(once.xp,before+10,'First completion should grant 10 XP.');
 assert.equal(once.reward,true,'XP reward must be recorded.');
 await page.locator('#v90MarkDone').click();
 await page.locator('#v90MarkDone').click();
 const twice=await page.evaluate(()=>({xp:State.xp,done:State.vocab90Completed['1']}));
 assert.equal(twice.xp,before+10,'Undo/re-completion must not duplicate XP.');
 assert.equal(twice.done,true);
 await page.locator('[data-v90-phase="1"]').click();
 await page.locator('[data-v90-select="31"]').click();
 await page.waitForFunction(()=>document.getElementById('v90SelectedTitle')?.textContent==='Day 31');
 if(await page.locator('#viTour.open').count())await page.keyboard.press('Escape');
 await page.locator('#v90NextDay').click();
 await page.waitForFunction(()=>document.getElementById('v90SelectedTitle')?.textContent==='Day 32');
 await page.locator('#v90Search').fill('intrepid');
 await page.locator('#v90SearchResults .v90-search-hit').first().waitFor({state:'visible',timeout:15000});
 await page.locator('#v90SearchResults [data-v90-open-day="1"]').first().click();
 await page.waitForFunction(()=>document.getElementById('v90SelectedTitle')?.textContent==='Day 01');
 assert.equal(await page.locator('#v90SearchResults').isHidden(),true);
 await page.locator('[data-v90-mode="all"]').click();
 await page.locator('#v90AllContent [data-v90-article="90"]').waitFor({state:'attached',timeout:15000});
 assert.equal(await page.locator('#v90AllContent [data-v90-article]').count(),90);
 await page.setViewportSize({width:390,height:844});
 const fits=await page.evaluate(()=>{const shell=document.querySelector('.v90-shell');return !!shell&&shell.getBoundingClientRect().right<=window.innerWidth+1;});
 assert.equal(fits,true,'Course should fit a narrow mobile viewport.');
 assert.deepEqual(pageErrors,[],'Vocab90 triggered an uncaught browser error.');
 console.log('Vocab90 browser smoke passed: navigation, search, all-days reading, mobile fit, completion, and one-time XP.');
}finally{await browser.close();}
